<?php
defined('COREPATH') or exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Get All Configuration Files
|--------------------------------------------------------------------------
| 
| Load all configuration files here
|
*/
function getConfigFiles()
{
    $files = glob(ROOTPATH . "config" . DIRECTORY_SEPARATOR . "*.php");
    $exclude = ['autoload', 'constants', 'database', 'hooks', 'profiler', 'commands', 'cached_config'];

    foreach ($files as $file) {
        $skip = false;
        foreach ($exclude as $name) {
            if (stripos($file, $name) !== false) {
                $skip = true;
                break;
            }
        }
        if (!$skip) yield $file;
    }
}

/*
|--------------------------------------------------------------------------
| Check if cache is valid (newer than all config files)
|--------------------------------------------------------------------------
| @param mixed $cacheFile
| @return bool
|
*/
function isCacheValid($cacheFile)
{

    if (!file_exists($cacheFile)) {
        return false;
    }

    $cacheTime = filemtime($cacheFile);

    // Check if any config file is newer than cache
    foreach (getConfigFiles() as $file) {
        if (filemtime($file) > $cacheTime) {
            return false; // Cache is outdated
        }
    }

    return true; // Cache is valid
}

/*
|--------------------------------------------------------------------------
| Create cache directory if it doesn't exist
|--------------------------------------------------------------------------
| 
|
*/
function ensureCacheDirectory($cacheFile)
{
    $cacheDir = dirname($cacheFile);
    if (!is_dir($cacheDir)) {
        if (!mkdir($cacheDir, 0755, true)) {
            // Fallback: use system temp directory
            return sys_get_temp_dir() . DIRECTORY_SEPARATOR . 'cached_config.php';
        }
    }
    return $cacheFile;
}

/*
|--------------------------------------------------------------------------
| Convert array to modern PHP array syntax
|--------------------------------------------------------------------------
|
*/
function arrayToModernSyntax($array, $indent = 0)
{

    if (!is_array($array)) {
        return var_export($array, true);
    }

    $isIndexed = array_keys($array) === range(0, count($array) - 1);
    $spaces = str_repeat('    ', $indent);
    $result = "[\n";

    foreach ($array as $key => $value) {
        $result .= $spaces . '    ';

        if (!$isIndexed) {
            $result .= var_export($key, true) . ' => ';
        }

        if (is_array($value)) {
            $result .= arrayToModernSyntax($value, $indent + 1);
        } else {
            $result .= var_export($value, true);
        }

        $result .= ",\n";
    }

    $result .= $spaces . ']';
    return $result;
}

/*
|--------------------------------------------------------------------------
| Save config array to cache file
|--------------------------------------------------------------------------
|
*/
function saveConfigCache($cacheFile, array $configData)
{
    $cacheDir = dirname($cacheFile);

    if (!is_dir($cacheDir)) {
        if (!mkdir($cacheDir, 0755, true)) {
            error_log("ConfigLoader: Failed to create cache directory: {$cacheDir}");
            return false;
        }
    }

    $cacheContent = "<?php\n";
    $cacheContent .= "defined('COREPATH') or exit('No direct script access allowed');\n\n";
    $cacheContent .= "// Config cache generated on " . date('Y-m-d H:i:s') . "\n";
    $cacheContent .= "// This file is automatically generated. Do not edit manually.\n\n";
    $cacheContent .= "return " . arrayToModernSyntax($configData) . ";\n";

    // Atomic write to prevent corruption
    $tempFile = $cacheFile . '.tmp';

    if (file_put_contents($tempFile, $cacheContent, LOCK_EX) !== false) {
        if (rename($tempFile, $cacheFile)) {
            return true;
        } else {
            // Clean up temp file if rename fails
            @unlink($tempFile);
        }
    }

    error_log("ConfigLoader: Failed to write cache file: {$cacheFile}");
    return false;
}

/*
|--------------------------------------------------------------------------
| MAIN CONFIGURATION LOADING LOGIC
|--------------------------------------------------------------------------
*/

// Static variable to prevent multiple loads in same request
static $configsLoaded = false;

if (! $configsLoaded) {
    // Define cache file location
    $cacheFile = ROOTPATH . 'config' . DIRECTORY_SEPARATOR . 'cached_config.php';

    // Ensure cache directory exists
    $cacheFile = ensureCacheDirectory($cacheFile);

    // Try to load from cache first
    if (isCacheValid($cacheFile) && config_item('enable_config_cache') !== false) {
        // FAST PATH: Load from cache
        $cachedConfig = include $cacheFile;

        if (is_array($cachedConfig)) {
            // Merge cached config with existing global $config
            $config = isset($config) ? array_merge($config, $cachedConfig) : $cachedConfig;
            $configsLoaded = true;

            // Optional: Log cache hit for debugging
            if (defined('ENVIRONMENT') && ENVIRONMENT === 'development') {
                error_log("ConfigLoader: Loaded from cache ({$cacheFile})");
            }
        } else {
            // Cache file is corrupted, delete it and reload
            @unlink($cacheFile);
            error_log("ConfigLoader: Cache file corrupted, deleted and will reload");
        }
    }

    // If cache loading failed or cache was invalid, load fresh configs
    if (!$configsLoaded) {
        // SLOW PATH: Load fresh configs and cache them
        $freshConfig = [];
        $loadedFiles = [];

        foreach (getConfigFiles() as $file) {
            // Create isolated scope for each config file
            $tempConfig = [];

            try {
                // Use a closure to create proper isolation
                $loadConfig = function ($configFile) {
                    $config = []; // Local scope variable
                    include $configFile;
                    return $config;
                };

                $fileConfig = $loadConfig($file);

                // Merge this file's config
                if (is_array($fileConfig) && !empty($fileConfig)) {
                    $freshConfig = array_merge($freshConfig, $fileConfig);
                    $loadedFiles[] = basename($file);
                }
            } catch (ParseError $e) {
                // Log parse errors but continue loading other files
                error_log("ConfigLoader: Parse error in {$file}: " . $e->getMessage());
            } catch (Error $e) {
                // Log other errors but continue
                error_log("ConfigLoader: Error loading {$file}: " . $e->getMessage());
            } catch (Exception $e) {
                // Log exceptions but continue
                error_log("ConfigLoader: Exception loading {$file}: " . $e->getMessage());
            }
        }

        if (config_item('enable_config_cache') !== false) {
            saveConfigCache($cacheFile, $freshConfig);
            // Optional: Log cache creation for debugging
            if (defined('ENVIRONMENT') && ENVIRONMENT === 'development') {
                error_log("ConfigLoader: Created cache with " . count($loadedFiles) . " files: " . implode(', ', $loadedFiles));
            }
        }

        // Merge fresh config with existing global $config
        $config = isset($config) ? array_merge($config, $freshConfig) : $freshConfig;
        $configsLoaded = true;

        // Force garbage collection after loading many files
        if (function_exists('gc_collect_cycles')) {
            gc_collect_cycles();
        }
    }
}

/*
|--------------------------------------------------------------------------
| OPTIONAL: CACHE MANAGEMENT FUNCTIONS
|--------------------------------------------------------------------------
|
| These functions are available for manual cache management if needed
*/
if (! function_exists('clear_config_cache')) {
    /**
     * Clear the config cache file
     * Call this after adding/removing config files
     */
    function clear_config_cache()
    {
        $cacheFile = ROOTPATH . 'config' . DIRECTORY_SEPARATOR . 'cached_config.php';
        if (file_exists($cacheFile)) {
            return unlink($cacheFile);
        }
        return true; // File doesn't exist, so it's "cleared"
    }
}

if (! function_exists('is_config_cache_enabled')) {
    /**
     * Check if config caching is enabled
     * @return bool
     */
    function is_config_cache_enabled()
    {
        global $config;

        $config['enable_config_cache'] = config_item('enable_config_cache');

        if (!isset($config['enable_config_cache'])) {
            return true; // Default to enabled for backward compatibility
        }

        return ($config['enable_config_cache'] === true ||
            $config['enable_config_cache'] === 'true' ||
            $config['enable_config_cache'] === '1' ||
            $config['enable_config_cache'] === 1);
    }
}

if (! function_exists('get_config_cache_info')) {
    /**
     * Get information about the config cache
     * Useful for debugging
     */
    function get_config_cache_info()
    {
        $cacheFile = ROOTPATH . 'config' . DIRECTORY_SEPARATOR . 'cached_config.php';

        $info = [
            'cache_enabled' => is_config_cache_enabled(),
            'exists' => file_exists($cacheFile)
        ];

        if (!$info['exists']) {
            return $info;
        }

        $cacheTime = filemtime($cacheFile);
        $cacheSize = filesize($cacheFile);

        // Count config files
        $configFiles = [];
        foreach (getConfigFiles() as $file) {
            $configFiles[] = basename($file);
        }

        return array_merge($info, [
            'file' => $cacheFile,
            'size' => $cacheSize,
            'size_human' => number_format($cacheSize / 1024, 2) . ' KB',
            'created' => date('Y-m-d H:i:s', $cacheTime),
            'age_seconds' => time() - $cacheTime,
            'is_valid' => $info['cache_enabled'] ? isCacheValid($cacheFile) : false,
            'config_files_count' => count($configFiles),
            'config_files' => $configFiles
        ]);
    }
}
